version: '3'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: profile-backend
    ports:
      - "3000:3000"
    env_file:
      - ./api/.env
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - PINECONE_INDEX=${PINECONE_INDEX:-semantic-search}
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4 