services:
  backend:
    build: .
    container_name: profile-backend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped 